import Head from "next/head";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import LeftSide from "@/components/LeftSide";
import RightSide from "@/components/RightSide";
import { motion } from "framer-motion";
import Banner from "@/components/Banner";
import About from "@/components/About";
import Experience from "@/components/Experience";
import Projects from "@/components/Projects";
import Archive from "@/components/Archive";
import Contact from "@/components/Contact";
import Footer from "@/components/Footer";
import { Analytics } from "@vercel/analytics/react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Khai Hoang - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/*note change favicon*/}
      </Head>
      <main
        className="w-full h-screen bg-white dark:bg-bodyColor font-bodyFont text-textLight overfow-x-hidden overflow-y-scroll scrollbar scrollbar-track-textDark/20
      scrollbar-thumb-textDark/60"
      >
        <Navbar></Navbar>
        <div className="w-full h-[88vh] xl:flex items-center gap-20 justify-between">
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 1.5 }}
            className="hidden xl:inline-flex w-32 h-full fixed left-0 bottom-0"
          >
            <LeftSide></LeftSide>
          </motion.div>
          <Banner></Banner>
          <div className="h-[88vh] p-4 w-full mx-auto">
            <About></About>
            <Experience></Experience>
            <Projects></Projects>
            <Archive></Archive>
            <Contact></Contact>
            <Footer></Footer>
          </div>
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 1.5 }}
            className="hidden xl:inline-flex w-32 h-full fixed right-0 bottom-0"
          >
            <RightSide></RightSide>
          </motion.div>
        </div>
      </main>
      <Analytics />
    </>
  );
}
